### PR TITLE
Add translations for debug:theme:keys.

### PR DESCRIPTION
**Pull request by DuaelFr**
See https://github.com/hechoendrupal/drupal-console/pull/3361

### CODE REVIEW

**Comment by enzolutions** [comment]
HI @DuaelFr 

Thanks for your contribution.

I have a question, the command theme:keys:debug is not in the list of our commands, where do you find that command?

**Comment by DuaelFr** [comment]
Hi @enzolutions 
I've put the link to the open PR in the first comment. This feature is being developped right now. :)

**Comment by enzolutions** [comment]
OK @DuaelFr, let me know when is ready to test.

I am wondering if you could be interested in contributing to complete French translation of Drupal Console?

**Comment by DuaelFr** [comment]
PR updated to follow the command development evolution.

@enzolutions I don't have much time to use on these translations but I can try to help a bit :)

**Comment by enzolutions** [comment]
Thanks @DuaelFr

**Comment by jmolivas** [comment]
@DuaelFr  Thanks for your contribution, your PR was merged. This will be included in the next release.

**Pull request merged**
